name: Docker Run

on: push

jobs:
  DockerRun:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reporitory
        uses: actions/checkout@v4

      - name: Build Docker file
        run: docker build . | tee containers.log
        
      - name: List all Docker Containers
        run: |
            grep -o '[a-fA-F0-9]{64}' containers.log
            # echo "IMAGE_NAME>>$IMAGE_NAME" >> GITHUB_ENV
            # docker run $IMAGE_NAME
            docker ps -a

